### ISSUE TITLE
to char* issue

### ISSUE THREAD

**Issue by Xed0sS** [unterumarmung/fixed_string#45]
https://github.com/JustasMasiulis/xorstr
constexpr fixstr::fixed_string foo = xor ("foo"); // error because is not const char*

So it doesn't works, fix it.

**Comment by unterumarmung** [comment]
First of all, there's no constructor from either `char*` or `const char*` because it's not possible to create a fixed string from a `const char*`. It has been discussed in #44.

Second. Your library looks interesting. But I guess there is a problem with the API. If you aim for compile-time, you should return a const reference to the array of the encrypted string, not const pointer.

**Comment by Xed0sS** [comment]
Anyway it doesn't works with ur fixed_string, for std::string it works fine, just fix that and it will be good.

**Comment by unterumarmung** [comment]
Again, the problem in not with fixed_string library, but with xorstr. I explained it to you and gave a direction to do further investigation. If you do not understand it, it is NOT my problem, but yours.

Also, `fixstr::fixed_string` and `std::string` are NOT fully interchangeable.

If you need something to be fixed, you are more than welcome to fork the library and do it yourself.
